version: '3.8'
services: 
  server:
    container_name: nginx
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    container_name: php
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    container_name: composer
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  # artisan:
  #   container_name: artisan
  # npm:
  #   container_name: npm
    